---
os: linux
dist: bionic

language: python
python: "3.8"
cache: pip
install: "pip install $(pipenv lock --requirements)"
script:
  - yamllint -c .yamllint .
  - ansible-lint .

notifications:
  irc:
    channels:
      - "ircs://chat.freenode.net:6697/##jwf"
    template:
      - "[%{repository_name}:%{branch}@%{commit} - build #%{build_number}] CI %{result}! (%{build_url})"
    on_success: change
    on_failure: always
